Try combining old and new cmake files and check that macos still builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,37 +14,37 @@ jobs:
       fail-fast: false
       matrix:
         config:
-          - os_name: windows
-            os_runner: windows-latest
-            arch: x86_64
-            python_exe: python
-            find_package_cmd: find build -maxdepth 1 -name '*.exe' | head -n 1
-            cmake_generator: "Visual Studio 17 2022"
-            cmake_toolset: "v142,host=x64"
-            cmake_platform_arch: "x64"
-            opencv_setup_cmd: |
-              choco install opencv --version=4.8.0 --yes --force
-              OPENCV_INSTALLED_PATH="C:/tools/opencv/build"
-              if [ -d "$OPENCV_INSTALLED_PATH" ]; then
-                echo "OpenCV_DIR=${OPENCV_INSTALLED_PATH}" >> $GITHUB_ENV
-                echo "Successfully set OpenCV_DIR to ${OPENCV_INSTALLED_PATH}"
-              else
-                echo "Error: OpenCV build directory not found at ${OPENCV_INSTALLED_PATH} after choco install."
-                ls -R /c/tools # List directories to help debug
-                ls -R /c/ProgramData/chocolatey/lib
-                exit 1
-              fi
-          # - os_name: macos
-          #   os_runner: macos-14
-          #   arch: arm64
-          #   python_exe: python3
-          #   find_package_cmd: find build -maxdepth 1 -name '*.dmg' | head -n 1
-          #   cmake_generator: ""
-          #   cmake_toolset: ""
-          #   cmake_platform_arch: ""
+          # - os_name: windows
+          #   os_runner: windows-latest
+          #   arch: x86_64
+          #   python_exe: python
+          #   find_package_cmd: find build -maxdepth 1 -name '*.exe' | head -n 1
+          #   cmake_generator: "Visual Studio 17 2022"
+          #   cmake_toolset: "v142,host=x64"
+          #   cmake_platform_arch: "x64"
           #   opencv_setup_cmd: |
-          #     brew install opencv@4
-          #     echo "OpenCV_DIR=$(brew --prefix opencv@4)/lib/cmake/opencv4" | tee -a $GITHUB_ENV
+          #     choco install opencv --version=4.8.0 --yes --force
+          #     OPENCV_INSTALLED_PATH="C:/tools/opencv/build"
+          #     if [ -d "$OPENCV_INSTALLED_PATH" ]; then
+          #       echo "OpenCV_DIR=${OPENCV_INSTALLED_PATH}" >> $GITHUB_ENV
+          #       echo "Successfully set OpenCV_DIR to ${OPENCV_INSTALLED_PATH}"
+          #     else
+          #       echo "Error: OpenCV build directory not found at ${OPENCV_INSTALLED_PATH} after choco install."
+          #       ls -R /c/tools # List directories to help debug
+          #       ls -R /c/ProgramData/chocolatey/lib
+          #       exit 1
+          #     fi
+          - os_name: macos
+            os_runner: macos-14
+            arch: arm64
+            python_exe: python3
+            find_package_cmd: find build -maxdepth 1 -name '*.dmg' | head -n 1
+            cmake_generator: ""
+            cmake_toolset: ""
+            cmake_platform_arch: ""
+            opencv_setup_cmd: |
+              brew install opencv@4
+              echo "OpenCV_DIR=$(brew --prefix opencv@4)/lib/cmake/opencv4" | tee -a $GITHUB_ENV
           # - os_name: linux
           #   os_runner: ubuntu-latest
           #   arch: x86_64
